### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by aarondl** [bgentry/speakeasy#12]
Can we get the license for the unix portion then? The original library was MIT, would be grateful if this ended up MIT as well.

**Comment by onlyjob** [comment]
It is important to document all licenses (and copyrights) as well at to commit full text of the license.

**Comment by onlyjob** [comment]
Blake, it would be great if you could add your own copyright statement and license grant. Thank you.

**Comment by euank** [comment]
ping @bgentry

**Comment by bgentry** [comment]
added an MIT license for non-Windows portions, sorry this sat for so long.

**Comment by euank** [comment]
Thanks!
