### ISSUE TITLE
build fails on solaris platform

### ISSUE THREAD

**Issue by ptribble** [bgentry/speakeasy#8]
speakeasy won't build on solaris.

The fix is so simple it doesn't need a patch; add solaris to the list of supported platforms on line 7 of speakeasy_unix.go

(after this change, etcdctl builds fine for me on solaris/illumos platforms)

**Comment by bgentry** [comment]
@ptribble sounds like a *tiny* patch to me ;) Would you mind submitting a PR for this?

**Comment by doublerebel** [comment]
closed with #10?

**Comment by bgentry** [comment]
Should be. Thanks!
